# Generated by Django 4.0.4 on 2022-04-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='Something to do.', max_length=200),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
