# Generated by Django 4.0.4 on 2022-04-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Category', max_length=200)),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
