# Generated by Django 4.0.4 on 2022-04-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
