# Generated by Django 4.0.4 on 2022-04-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='year_in_school',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=2),
        ),
    ]
