# Generated by Django 4.0.4 on 2022-04-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_todo_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='year_in_school',
            new_name='Priority',
        ),
    ]
