# Generated by Django 4.0.4 on 2022-04-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_category_options_event_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('r', 'removed'), ('d', 'done'), ('a', 'active')], default='active', max_length=200),
        ),
    ]
