# Generated by Django 4.0.4 on 2022-04-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_event_event_time_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('r', 'removed'), ('a', 'active'), ('d', 'done')], default='active', max_length=200),
        ),
    ]
