# Generated by Django 4.0.4 on 2022-04-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('d', 'done'), ('r', 'removed')], default='active', max_length=200),
        ),
    ]
