# Generated by Django 4.0.4 on 2022-04-12 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('price_sm_0', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('price_sm_1', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('price_sm_2', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('price_sm_3', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('price_sm_4', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('price_lg_0', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('price_lg_1', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('price_lg_2', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('price_lg_3', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('price_lg_4', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProperOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('order_done', models.BooleanField(default=False)),
                ('order_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('already_ordered', models.BooleanField(default=False)),
                ('pizza_size', models.CharField(choices=[('sm', 'small'), ('lg', 'large')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4)),
                ('add_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('in_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pizza.properorder')),
                ('pizzatype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.pizzatype')),
                ('toppings', models.ManyToManyField(blank=True, to='pizza.pizzatopping')),
            ],
        ),
    ]
